stages:
  - prepare
  - build


download-artifacts:
  stage: prepare
  script:
    - ls -alt iep-node-artifacts
    - echo "CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}"
  needs:
    - project: infinity-economics/iep-node
      ref: ${CI_COMMIT_REF_NAME}
      job: prepare-iep-node-artifacts
      artifacts: true

build-windows:
  image: adoptopenjdk/openjdk11:alpine-slim
  stage: build
  before_script:
    - |
      apk add --update --no-cache bash python3 py3-pip
  script:
    - |
      ./create-win-installer.sh ${PWD}/iep-node-artifacts
  artifacts:
    paths:
      - ./build/distributions/iep-installer-node.exe
  tags:
    - ci-cd

build-linux:
  image: adoptopenjdk/openjdk11:alpine-slim
  stage: build
  before_script:
    - |
      apk add --update --no-cache bash
  script:
    - |
      ./create-linux-installer.sh ${PWD}/iep-node-artifacts
  artifacts:
    paths:
      - ./build/distributions/iep-node-installer.run
  tags:
    - ci-cd

build-mac:
  image: adoptopenjdk/openjdk11:alpine-slim
  stage: build
  before_script:
    - |
      apk add --update --no-cache bash
  script:
    - |
      ./create-mac-installer.sh ${PWD}/iep-node-artifacts
  artifacts:
    paths:
      - ./build/distributions/iep-node-installer.app
  tags:
    - ci-cd