jreBundleVersion=21.0.5+11
jfxBundleVersion=21.0.2
jreBundleFileName=OpenJDK21U-jre_x64_mac_hotspot_21.0.5_11.tar.gz
jreBundleFileDir=jdk-21.0.5+11-jre/Contents
jfxBundleFileName=openjfx-21.0.2_osx-x64_bin-sdk.zip
