jreBundleVersion=21.0.5+11
jfxBundleVersion=21.0.2
jreBundleFileName=OpenJDK21U-jre_x64_windows_hotspot_21.0.5_11.zip
jreBundleFileDir=jdk-21.0.5+11-jre
jfxBundleFileName=openjfx-21.0.2_windows-x64_bin-sdk.zip
